### ISSUE TITLE
Bump version of fs2 to 0.10 instead of 0.9

### ISSUE THREAD

**Issue by sdjamaa** [criteo/cuttle#197]
lolhttp is using fs2 in version 0.10 and cuttle is not wiring explicitly any dependency thus failing to compile when using the newest version of lolhttp (fs2.Strategy has been removed in 0.10 in favor to scala.concurrent.ExecutionContext).

**Comment by dufrannea** [comment]
Hi @sdjamaa, we are currently in the process of migrating to the latest version of lolhttp, this should be done this week.

**Comment by eryshev** [comment]
Close this issue as it's resolved by #201.
