### ISSUE TITLE
Questions about retry strategy and pausing 

### ISSUE THREAD

**Issue by ouchxp** [criteo/cuttle#276]
Hi thanks for the awesome job for building this framework! 

I would like to use this library to schedule some cron job, but for my job what I would like to do is execute jobs without retrying since our cron job is time sensitive, if the time passed, there is no point to rerun the job for previous hour. 

I assume that if I set the retry duration to `Long.MaxValue`, cuttle will still try to schedule these retry executions, and makes the retry queue grow forever, Is that right? 
Is there any way to let the execution fail and without retrying?

Another thing is sometimes we would like to pause the cron jobs for a while, and skip all the executions for few hours, is there any way to achieve that?

Thanks!

**Comment by guillaumebort** [comment]
Hi!

Yes the timeseries scheduler is a bit different of a cron scheduler. It won't allow any period of time without successful executions.

You can still make it work by handling the logic into your job code, and for example returning a `Future.successful(Completed)` if you think that the scheduler should consider the task as done. The drawback here is that you won't see failing execution directly in the executions list (but you can still log an error in the log itself, so depending of your use case it can work for you).

One think to keep in mind is that we designed cuttle so it is possible to have different scheduling mechanism with different semantic. And clearly a CronScheduler makes a lot of sense. Or you can even use cuttle with custom code as scheduler.

This is not really true at the moment as the Timeseries one is a bit tied to the current design. But we are working to fix that currently. I just opened a pull-request to make an example of a custom scheduler. See #277.

**Comment by ouchxp** [comment]
I'll try find out what I can do. Thanks a lot for the quick answering!
